server:
  port: 8003
spring:
  application:
    name: back
    nacos:
      server-addr: 127.0.0.1:8848
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/real_estate_manager?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=PRC&useSSL=false
    username: root
    password: huangyixuan
mybatis-plus:
  mapper-locations:
    - classpath:xml/*.xml